let currentTab="homeTab";const $=id=>document.getElementById(id);
function render(){const mala=state.todayJaps%108;$("homeJaps").textContent=state.todayJaps;$("homeMalas").textContent=Math.floor(state.todayJaps/108);$("homeTotal").textContent=state.totalJaps;["japMantra","circleMantra","homeMantra","profileMantra"].forEach(id=>$(id).textContent=state.selectedNaam);$("circleCount").textContent=mala;$("progressText").textContent=`${mala} / 108`;$("progressBar").style.width=`${mala/108*100}%`;$("profileName").textContent=state.userName||"Sadhak";$("profileTotal").textContent=state.totalJaps;$("profileMala").textContent=state.totalMalas;$("profileStreak").textContent=state.streak||0;const [mt,mx]=milestoneInfo();$("milestoneTitle").textContent=mt;$("milestoneText").textContent=mx;renderNaams();renderBeads()}
function renderBeads(){let html="";const n=state.todayJaps%108;for(let i=0;i<108;i++)html+=`<i class="${i<n?'done':''}"></i>`;$("beads").innerHTML=html}
function renderNaams(){$("naamList").innerHTML=state.naams.map(n=>`<button type="button" class="naam-option ${n===state.selectedNaam?'selected':''}" data-name="${encodeURIComponent(n)}"><span>🪷 ${escapeHtml(n)}</span><span>${n===state.selectedNaam?'✓':'›'}</span></button>`).join("")}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showTab(id){currentTab=id;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));window.scrollTo({top:0,behavior:'instant'})}
function toast(t){$("toast").textContent=t;$("toast").classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>$('toast').classList.remove('show'),1700)}
function tapJap(){const before=state.todayJaps;incrementJap();beep();if(navigator.vibrate)navigator.vibrate(8);const f=$("flash");f.classList.remove('pop');void f.offsetWidth;f.classList.add('pop');render();if((before+1)%108===0){malaSound();toast('🌸 1 Mala Complete • 108 Jap 🙏')}}
function init(){loadState();setTimeout(()=>{splashSound();$("splash").classList.add('hidden');if(state.userName)$("mainApp").classList.remove('hidden');else $("onboarding").classList.remove('hidden');render()},2300);
 document.querySelectorAll('#mantraChoices button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#mantraChoices button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$("customMantraInput").classList.toggle('hidden',b.dataset.mantra!=='Custom');if(b.dataset.mantra!=='Custom')$("customMantraInput").value=''});
 $("startBtn").onclick=()=>{const name=$("userNameInput").value.trim();const selected=document.querySelector('#mantraChoices .selected');if(!name)return toast('अपना नाम लिखिए');if(!selected)return toast('जाप नाम चुनिए');let m=selected.dataset.mantra;if(m==='Custom'){m=$("customMantraInput").value.trim();if(!m)return toast('Custom Naam लिखिए');if(!state.naams.includes(m))state.naams.push(m)}state.userName=name;state.selectedNaam=m;state.lastDate=today();saveState();$("onboarding").classList.add('hidden');$("mainApp").classList.remove('hidden');render();showTab('homeTab');toast('🙏 Naam Smaran शुरू करें')};
 document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$("japCircle").onclick=tapJap;$("undoBtn").onclick=()=>{if(undoJap()){render();toast('Last Jap undone')}else toast('Undo के लिए Jap नहीं है')};$("resetBtn").onclick=()=>{if(state.todayJaps===0)return toast('Mala पहले से 0 है');state.todayJaps=0;saveState();render();toast('Mala reset हो गई')};$("homeStart").onclick=()=>showTab('japTab');
 $("naamList").onclick=e=>{const b=e.target.closest('.naam-option');if(!b)return;const n=decodeURIComponent(b.dataset.name);setNaam(n);render();toast('Naam selected: '+n)};
 $("addNaam").onclick=()=>{const n=$("newNaam").value.trim();if(!n)return toast('Naam लिखिए');if(!state.naams.includes(n))state.naams.push(n);state.selectedNaam=n;saveState();$("newNaam").value='';render();toast('Naam added')};
 $("soundToggle").onclick=()=>{soundOn=!soundOn;$("soundToggle").textContent=soundOn?'🔊':'🔇';if(soundOn)tone(700,.12,.05)};$("editProfile").onclick=()=>{const n=prompt('आपका नाम',state.userName);if(n&&n.trim()){state.userName=n.trim();saveState();render()}};
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)render()});
}
init();
